version: '3'

services:
  # jaeger-clickhouse-binaries:
  #   build:
  #     context: .
  #     dockerfile: ./clickhouse/Dockerfile
  #     args:
  #       GOOS: linux
  #       GOARCH: arm64
  #   volumes:
  #     - output:/app/output
  jaeger:
    image: jaegertracing/all-in-one:1.32.0
    container_name: jaeger
    restart: always
    ports:
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "6831:6831/udp"
    environment:
      - JAEGER_DISABLED=false
      - SPAN_STORAGE_TYPE=grpc-plugin
    volumes:
      - "./output:/data"
    command: >
      --query.ui-config=/data/jaeger-ui.json
      --grpc-storage-plugin.binary=/data/jaeger-clickhouse-linux-arm64
      --grpc-storage-plugin.configuration-file=/data/config.yaml
      --grpc-storage-plugin.log-level=debug
    links:
      - clickhouse
    user: "501"
    # depends_on:
    #   - build-binaries
  clickhouse:
    image: clickhouse/clickhouse-server:22
    container_name: some-clickhouse-server
    ports:
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
