version: '3'

services:
  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - "16686:16686"
      - "6831:6831/udp"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
      STORAGE_TYPE: grpc-plugin
      STORAGE_PLUGIN_BINARY: /go/bin/clickhouse
      STORAGE_PLUGIN_CONFIGURATION: '{"dsn":"tcp://clickhouse:9000","database":"jaeger","table":"jaeger"}'
      SPAN_STORAGE_TYPE: grpc-plugin
      SPAN_STORAGE_PLUGIN_BINARY: /go/bin/clickhouse
      SPAN_STORAGE_PLUGIN_CONFIGURATION: '{"dsn":"tcp://clickhouse:9000","database":"jaeger","table":"jaeger"}'
    depends_on:
      - clickhouse